# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20171112_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='random'),
            preserve_default=False,
        ),
    ]
