# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20171116_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publish',
            new_name='publish_date',
        ),
    ]
